SET SERVEROUTPUT ON;
DECLARE CURSOR c IS SELECT title,price FROM book ORDER BY price DESC; BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(c%ROWCOUNT||'. '||r.title||' - Rs.'||r.price); EXIT WHEN c%ROWCOUNT=5; END LOOP; END;
/